# Generated by Django 4.2.2 on 2023-06-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_carouselimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='description',
        ),
    ]
