# Generated by Django 4.2.2 on 2023-06-23 14:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_indexpage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_url', models.URLField(blank=True, null=True)),
                ('opening_hours', models.CharField(max_length=255)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
