# Generated by Django 4.2.2 on 2023-06-23 14:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='header',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='home_url',
            field=models.URLField(null=True),
        ),
    ]
