# Generated by Django 4.2.2 on 2023-06-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_footer_alter_header_options_header_home_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_text',
            field=models.TextField(null=True),
        ),
    ]
