# Generated by Django 4.2.2 on 2023-06-29 22:25

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('index', '0012_requestpagesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpage',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requestpage',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='requestpage',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='requestpage',
            name='home_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='requestpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='RequestPageSnippet',
        ),
    ]
