# Generated by Django 4.2.2 on 2023-06-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_requestpage_address_requestpage_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpage',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
