# Generated by Django 4.2.2 on 2023-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_requestpage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpage',
            name='intro',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='requestpage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
    ]
