# Generated by Django 4.2.2 on 2023-06-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_requestpage_intro_alter_requestpage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='earn_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='service_url',
            field=models.URLField(null=True),
        ),
    ]
