# Generated by Django 4.2.2 on 2023-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_header_earn_url_header_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='earn_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='home_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='service_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
