# Generated by Django 4.2.2 on 2023-06-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_alter_header_earn_url_alter_header_home_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='earn_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='home_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='service_url',
            field=models.URLField(null=True),
        ),
    ]
