# Generated by Django 4.2.2 on 2023-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_earnpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='earn_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='service_url',
            field=models.URLField(null=True),
        ),
    ]
